### ISSUE TITLE
BnB computation not bounded

### ISSUE THREAD

**Issue by murchandamus** [p2pderivatives/rust-bitcoin-coin-selection#19]
Bitcoin Core's BnB algorithm traverses the power set of the wallet's UTXO pool. While there are some optimizations¹ that allow skipping parts of the combination space that cannot yield solutions, the power set of n elements has 2<sup>n</sup> elements. Exhaustively searching this combination space can prompt extensive computations even with a small count of elements, which is why Bitcoin Core only considers a fixed count of combinations of 100'000.

This implementation currently only searches n² combinations, and the tests appear to operate on a small count of UTXOs. A useful test to highlight the issue could be crafted by creating a smallish wallet with 100–1'000 UTXOs and try to exhaustively search the input set candidates. I would expect this to cause issues especially once the BnB algorithm is amended to generate the complete power set.

----
¹ e.g. 1. Look-ahead: stop searching if remaining elements yield too little funds (already implemented), 2. Duplicates: skip equivalent input sets, e.g. if B+C are of the same output type and have the same value, having considered {A+B+D} allows skipping {A+C+D}., 3. no-improvement-possible: if adding more elements to the input set can only disimprove the fitness score and a valid input set has been found already, the subtree can be skipped as it can only score worse, etc.

**Comment by yancyribbens** [comment]
closed by https://github.com/p2pderivatives/rust-bitcoin-coin-selection/pull/28

**Comment by yancyribbens** [comment]
@murchandamus I'm ready to cut a new release.  I am wondering if you could check https://github.com/p2pderivatives/rust-bitcoin-coin-selection/pull/30 to make sure this closes the issue you opened.  Thanks!

**Comment by yancyribbens** [comment]
closed by https://github.com/p2pderivatives/rust-bitcoin-coin-selection/pull/30
